### ISSUE TITLE
Missing other starter kit modules on github

### ISSUE THREAD

**Issue by tamascsaba** [Kflash/rachelle#9]
I found sikky on npm, but github repo is unavalible :(

**Comment by Kflash** [comment]
@tamascsaba I know. It would be too many starter kit if I had everyone on Github. If you want I can email Sikky to you. There are mainly no big differences between them.

**Comment by tamascsaba** [comment]
@Kflash thx :+1: I'am an angular2 developer and I interested in angular2 support :) My e-mail: tamcsaba@gmail.com

**Comment by tamascsaba** [comment]
@Kflash ???

**Comment by Kflash** [comment]
@tamascsaba I'm here, but busy developing a TDD driven test runner ala Karma. 

Angular 2? What do you have in mind? Example of a configration would help.
